import type { NextPage } from 'next'
import Head from 'next/head'
import DataSelector from '../components/DataSelector'
import BarChart from '../components/D3/Barchart'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [state, setState] = useState([]); // has to start out empty or the droppable won't work
  const [data, setData] = useState({ cols: {}, classifications: null }); // has to start out empty or the droppable won't work

  return (
    <div >
      <Head>
        <title>Tableau Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DataSelector state={state} setState={setState} data={data} setData={setData} />
        <div className='ml-60 bg-blue-100 h-screen w-screen'>
          <div className='py-4 px-8 h-full w-full'>
            <BarChart data={[1, 2, 3]} xVar={'Country'} yVar={'Value'} />
          </div>
        </div>
      </main>
      {/* 
      <footer className='ml-60 flex items-center h-screen-1/12'>
        graphic
      </footer> */}
    </div>
  )
}

export default Home
