import type { NextPage } from 'next'
import Head from 'next/head'
import DataSelector from '../components/SideBar'
import BarChart from '../components/D3/Barchart'
import { useEffect, useState, useRef } from 'react'
import HeaderBar from '../components/HeaderBar'

const Home: NextPage = () => {
  const [state, setState] = useState([]); // has to start out empty or the droppable won't work
  const [data, setData] = useState({
    cols: {}, classifications: null, chartType: "BarChart", dark: false, bg: "#f8fafc", recentColors: ['#ff562e', '#0000bb', '#bb0091', '#f8005e']
  });

  useEffect(() => {
    setData({ ...data, dark: window.matchMedia('(prefers-color-scheme: dark)').matches })
  }, [])

  return (
    <div >
      <Head>
        <title>Tableau Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={data.dark ? 'w-screen h-screen dark' : 'w-screen h-screen'}>
        <DataSelector state={state} setState={setState} data={data} setData={setData} />
        <HeaderBar state={state} setState={setState} data={data} setData={setData} />
        <div className='h-full ml-60' style={{ background: data.bg }}>
          <div className='w-full h-full p-24'>
            <BarChart data={[1, 2, 3]} xVar={'Country'} yVar={'Value'} />
          </div>
        </div>
      </main>
      {/* 
      <footer className='flex items-center ml-60 h-screen-1/12'>
        graphic
      </footer> */}
    </div>
  )
}

export default Home
